# Generated by Django 4.2.7 on 2025-05-08 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import workflows.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('workflow_type', models.CharField(choices=[('MATRIX_ADDITION', 'Addition de matrices de grande taille'), ('MATRIX_MULTIPLICATION', 'Multiplication de matrices de grande taille'), ('ML_TRAINING', 'Entraînement de modèle machine learning'), ('CUSTOM', 'Workflow personnalisé')], default='MATRIX_ADDITION', max_length=30)),
                ('status', models.CharField(choices=[('CREATED', 'Créé'), ('VALIDATED', 'Validé'), ('SUBMITTED', 'Soumis'), ('SPLITTING', 'En découpage'), ('ASSIGNING', 'En attribution'), ('PENDING', 'En attente'), ('RUNNING', 'En exécution'), ('PAUSED', 'En pause'), ('PARTIAL_FAILURE', 'Échec partiel'), ('REASSIGNING', 'Réattribution'), ('AGGREGATING', 'Agrégation'), ('COMPLETED', 'Terminé'), ('FAILED', 'Échoué')], default='CREATED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.IntegerField(default=1)),
                ('tags', models.JSONField(default=list)),
                ('metadata', models.JSONField(default=dict)),
                ('max_execution_time', models.IntegerField(default=3600)),
                ('retry_count', models.IntegerField(default=3)),
                ('executable_path', models.CharField(blank=True, help_text="Chemin vers l'exécutable", max_length=500)),
                ('input_path', models.CharField(blank=True, help_text="Chemin des données d'entrée", max_length=500)),
                ('input_data_size', models.IntegerField(default=0, help_text="Taille des données d'entrée en Mo")),
                ('output_path', models.CharField(blank=True, help_text='Chemin où stocker les résultats', max_length=500)),
                ('estimated_resources', models.JSONField(default=dict, help_text='Ressources estimées pour le workflow (ex. RAM, CPU...)')),
                ('preferences', models.JSONField(default=dict, help_text='Critères souhaités pour les volontaires (type de volontaire, ressources disponibles...)')),
                ('workflow_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique du workflow', unique=True)),
                ('coordinator_workflow_id', models.UUIDField(blank=True, help_text='Identifiant du workflow venant du coordinnateur du système', null=True, unique=True)),
                ('owner', models.ForeignKey(default=workflows.models.get_default_owner, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
                'ordering': ['-created_at'],
            },
        ),
    ]
